### ISSUE TITLE
How Can I get QR base64 from qrcanvas with React

### ISSUE THREAD

**Issue by cgfeel** [gera2ld/qrcanvas-react#1]
code show as below
> https://codesandbox.io/s/infallible-sid-p3oim?file=/src/App.js

I wan't get the QR base64. How to do it? I can't get base64 data from HTML dom.

**Comment by gera2ld** [comment]
See https://codesandbox.io/s/busy-fast-bym2g?file=/src/App.js

**Comment by cgfeel** [comment]
@gera2ld THX
